server:
  port: 8082

spring:
  application:
    name: operador-service
  datasource:
    url: jdbc:h2:mem:operadordb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
